# Generated by Django 4.2.21 on 2025-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('user', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_deposits',
            field=models.ManyToManyField(blank=True, related_name='users_with_deposit', to='products.depositproducts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_savings',
            field=models.ManyToManyField(blank=True, related_name='users_with_saving', to='products.savingproducts'),
        ),
    ]
