# Generated by Django 4.2.8 on 2025-05-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('crdt_prdt_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('dcls_month', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('etc_note', models.TextField()),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=50)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('dly_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_lmt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(default='전세자금', max_length=50)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('dly_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_lmt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.savingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='RentLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpay_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_min', models.FloatField(blank=True, null=True)),
                ('lend_rate_max', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.rentloanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpay_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_min', models.FloatField(blank=True, null=True)),
                ('lend_rate_max', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.depositproducts')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('crdt_grad_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.creditloanproduct')),
            ],
        ),
    ]
