# Generated by Django 4.2.8 on 2025-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=50)),
                ('interest_type', models.CharField(blank=True, max_length=50, null=True)),
                ('min_rate', models.FloatField(null=True)),
                ('max_rate', models.FloatField(null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
    ]
