# Generated by Django 4.2.8 on 2025-05-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='interest_type',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='max_rate',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='min_rate',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='dly_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='erly_rpay_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='fin_co_subm_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='join_way',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_inci_expn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_lmt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrtg_type', models.CharField(blank=True, max_length=100, null=True)),
                ('mrtg_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('rpay_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rpay_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_min', models.FloatField(blank=True, null=True)),
                ('lend_rate_max', models.FloatField(blank=True, null=True)),
                ('lend_rate_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.loanproduct')),
            ],
        ),
    ]
