# Generated by Django 4.2.8 on 2025-05-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_loanproduct_interest_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_type', models.CharField(default='전세자금', max_length=50)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('loan_inci_expn', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('dly_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_lmt', models.TextField(blank=True, null=True)),
                ('dcls_month', models.CharField(blank=True, max_length=10, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('dcls_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RentLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpay_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rpay_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lend_rate_min', models.FloatField(blank=True, null=True)),
                ('lend_rate_max', models.FloatField(blank=True, null=True)),
                ('lend_rate_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.rentloanproduct')),
            ],
        ),
    ]
