# Generated by Django 4.2.8 on 2025-05-23 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rentloanproduct_rentloanoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(blank=True, max_length=20, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('pnsn_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('pnsn_kind_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('mntn_cnt', models.CharField(blank=True, max_length=50, null=True)),
                ('prdt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('prdt_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('dcls_rate', models.FloatField(blank=True, null=True)),
                ('guar_rate', models.FloatField(blank=True, null=True)),
                ('btrm_prft_rate_1', models.FloatField(blank=True, null=True)),
                ('btrm_prft_rate_2', models.FloatField(blank=True, null=True)),
                ('btrm_prft_rate_3', models.FloatField(blank=True, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
                ('sale_co', models.TextField(blank=True, null=True)),
                ('dcls_month', models.CharField(blank=True, max_length=10, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('dcls_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PensionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, max_length=50, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrv_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.CharField(blank=True, max_length=20, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.pensionproduct')),
            ],
        ),
    ]
