# Generated by Django 4.2.8 on 2025-05-23 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_pensionproduct_pensionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(blank=True, max_length=20, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('crdt_prdt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('crdt_prdt_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('cb_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dcls_month', models.CharField(blank=True, max_length=10, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('dcls_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type', models.CharField(blank=True, max_length=50, null=True)),
                ('crdt_lend_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('crdt_grad_1', models.FloatField(blank=True, null=True)),
                ('crdt_grad_4', models.FloatField(blank=True, null=True)),
                ('crdt_grad_5', models.FloatField(blank=True, null=True)),
                ('crdt_grad_6', models.FloatField(blank=True, null=True)),
                ('crdt_grad_10', models.FloatField(blank=True, null=True)),
                ('crdt_grad_11', models.FloatField(blank=True, null=True)),
                ('crdt_grad_12', models.FloatField(blank=True, null=True)),
                ('crdt_grad_13', models.FloatField(blank=True, null=True)),
                ('crdt_grad_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.creditloanproduct')),
            ],
        ),
    ]
